package com.chapter.errorhandlingwithexceptions;

public class Test {
    public static void main(String[] args) {
        for (String arg : args) {
            try {
                thrower(arg);
                System.out.println("Test \"" + arg +
                                   "\" didn't throw an exception");
            } catch (Exception e) {
            	System.out.println("Test \"" + arg +
                   "\" threw a " + e.getClass() +
                   "\n    with message: " +
                   e.getMessage());
            }
        }    
}
    
    static int thrower(String s) throws TestException {
    	try {
    		if (s.equals("divide")) {
    			int i = 0;
    			return i/i; 
    		}
    		if (s.equals("null")) {
    			s = null;
    			return s.length();
    		}
    		if (s.equals("test")) {
    			throw new TestException("Test message");
    		}
    		return 0;
    	} finally {
    		System.out.println("[thrower(\"" + s + "\") done]");
    	}
    }
}

class TestException extends Exception {
    TestException() { 
    	super(); 
    }
    
    TestException(String s) { 
    	super(s); 
    }
}
    